# Generated by Django 3.2.3 on 2021-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('agent_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=40, null=True)),
                ('working_area', models.CharField(blank=True, max_length=35, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'agents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cust_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=40)),
                ('cust_city', models.CharField(blank=True, max_length=35, null=True)),
                ('working_area', models.CharField(max_length=35)),
                ('cust_country', models.CharField(max_length=20)),
                ('grade', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('opening_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('receive_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outstanding_amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_no', models.CharField(max_length=17)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('ord_num', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('ord_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ord_date', models.DateField()),
                ('ord_description', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
